# -*- coding: utf-8 -*-
"""toy project on children getting placed or not

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g15YdxTumRcoZkRhmxIrrv0Y5N6ve7Xv
"""

import pandas as pd
import numpy as np

import pandas as pd
df= pd.read_csv('//content/placement.csv')

df.head()

df.shape

df = df.iloc[:,1:]

df.head()

#steps     
   
#1 preparations + EDA + FEATURE SELECTION
#Extract input and output goals
#Scale the vlaues
#Train the model
#Evaluate the model /model slection
#Deploy the model

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

"""extracting input and output goals

"""

x = df.iloc[:,0:2]
y = df.iloc[:,-1]

x

y.shape

"""train test split"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

x_train

y_train

x_test

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_train

x_test = scaler.transform(x_test)

x_test

from sklearn.linear_model import LogisticRegression

clf.fit(x_train,y_train)

Y_pred = +clf.predict(x_test)

y_test

from sklearn.metrics import accuracy_score

accuracy_score(y_test,Y_pred)

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x_train,y_train.values,clf=clf,legend=2)

import pickle

pickle.dump(clf,open('model.pkl','wb'))

